name: Push Check Go on Windows

# on: push

# jobs:
#   build:
#     strategy:
#       matrix:
#         go-version: [1.15.x, 1.16.x, 1.17.x, 1.18.x]
#         os: [windows-latest]
#     runs-on: ${{ matrix.os }}
#     steps:
#       - uses: actions/checkout@v2

#       - name: Set up Go
#         uses: actions/setup-go@v3
#         with:
#           go-version: ${{ matrix.go-version }}

#       - name: Unit Test
#         run: go test -v -gcflags=-d=checkptr=0 ./...
#         env:
#           GOMAXPROCS: 4
#           SONIC_NO_ASYNC_GC: 1